### ISSUE TITLE
i'm getting error

### ISSUE THREAD

**Issue by nefro313** [Coldcolin/QUIZ-FRONT#1]
<img width="1440" alt="Screenshot 2023-03-01 at 1 01 57 AM" src="https://user-images.githubusercontent.com/85278742/221959311-ae88cafa-fb76-4175-b1dc-c1f2a68d2e49.png">
hey bro .i getting this error (above i pined )while i working with your app .when i start the quiz into the quiz route i'm getting this  erorr

**Comment by nefro313** [comment]
+91 8593833872 this my mobile number. i hope you will reply very soon

**Comment by Coldcolin** [comment]
I believe you are getting an object instead of an array somewhere. I
couldn't tell from the error message, you could screenshot the console in
the Browser and send it to me.

**Comment by nefro313** [comment]
<img width="1440" alt="Screenshot 2023-03-01 at 11 33 36 PM" src="https://user-images.githubusercontent.com/85278742/222224257-8cfbbd18-6cee-466e-ab7b-5a05d9a23ec5.png">

**Comment by nefro313** [comment]
can you check the app is still running

**Comment by Coldcolin** [comment]
I just confrimed the API server was down, I'll redeploy and push

**Comment by Coldcolin** [comment]
I have updated  the API in the latest push, thanks for the notice, the App works fine now

**Comment by nefro313** [comment]
Now it's working.With your api is totally fine but the quiz-backend api is not working. I tried that api but it's not working. But I'm sure this error is getting from the backend. Can check tht quiz-backend is working or not.

**Comment by Coldcolin** [comment]
The Questions are coming from the database through the Server, so if you are getting questions and answers, then the server is up.

**Comment by nefro313** [comment]
I found the issue, first we have to POST the question and answer into the mongoDb database only then the front-end will fetch questions and answers. After the user login the front-end makes a GET request but here now it will return an empty array because the DB has no collection of data that is why it is showing the error. To solve the problem we have to manually make post requests  using Postman
